# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-17 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_details',
            name='role',
            field=models.CharField(default='manager', max_length=200),
            preserve_default=False,
        ),
    ]
