# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_details',
            name='staff_image',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.upload_staff_img),
        ),
    ]
