# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-01 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_details',
            name='staff_image',
            field=models.ImageField(default='http://sharegallerymedia.s3.amazonaws.com/staff/20180417182116.jpg', upload_to=gallery.models.upload_staff_img),
        ),
    ]
