# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-01 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180501_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_details',
            name='staff_image',
            field=models.ImageField(default='\\static\\imgs\x8180221130628.jpg', upload_to=gallery.models.upload_staff_img),
        ),
    ]
