# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180208_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('bio', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=gallery.models.upload_student_img)),
            ],
        ),
    ]
