# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20180220_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_details',
            name='staff_image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='student_img',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
