# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_details',
            name='staff_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
