# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staff_details_staff_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_details',
            name='user',
        ),
        migrations.DeleteModel(
            name='staff_details',
        ),
    ]
