# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(default='Anonymous', max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
