# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-24 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideimage',
            name='name',
            field=models.CharField(default='img', max_length=50),
            preserve_default=False,
        ),
    ]
