# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_slideimage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=260)),
            ],
        ),
        migrations.CreateModel(
            name='LandingContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
            ],
        ),
    ]
