# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 13:28
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_landingbox_landingcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingcontent',
            name='content',
            field=tinymce.models.HTMLField(default=' '),
            preserve_default=False,
        ),
    ]
