# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_landingcontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingbox',
            name='content',
            field=models.TextField(max_length=260),
        ),
    ]
