# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 13:31
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180502_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingbox',
            name='content',
            field=tinymce.models.HTMLField(max_length=260),
        ),
    ]
