# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_contact',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
