# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_info',
            name='check',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
    ]
