# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_contact_info_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_info',
            name='check',
        ),
    ]
