# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-01 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import information.models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('img', models.ImageField(default='http://sharegallerymedia.s3.amazonaws.com/staff/20180417182116.jpg', upload_to=information.models.upload_staff_img)),
            ],
        ),
    ]
