# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-18 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticky_Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='info_content',
            name='info',
            field=tinymce.models.HTMLField(),
        ),
    ]
