# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-01 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import information.models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_sponsers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsers',
            name='img',
            field=models.ImageField(default='\\static\\imgs\x8180221130628.jpg', upload_to=information.models.upload_staff_img),
        ),
    ]
