# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import information.models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_auto_20180501_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticky_note',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=information.models.upload_staff_img),
        ),
    ]
