# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', tinymce.models.HTMLField()),
            ],
        ),
    ]
